
type Bit    = 1 | 0
type Trit   = 2 | Bit
type Dit    = 3 | Trit
type Pentit = 4 | Dit
type Hexit  = 5 | Pentit
type Septit = 6 | Hexit
type Octit  = 7 | Septit
type Side = Hexit
type HotbarSlot = Octit | 8
type ClickSlotButton = HotbarSlot | 9 | 10 | OffhandSlot
type OffhandSlot = 40
type Difficulty = Dit
type HealSource = DamageSource
type KeyMods =
| 'key.keyboard.left.shift'
| 'key.keyboard.left.control'
| 'key.keyboard.left.alt'
| 'key.keyboard.left.shift+key.keyboard.left.control'
| 'key.keyboard.left.shift+key.keyboard.left.alt'
| 'key.keyboard.left.control+key.keyboard.left.alt'
| 'key.keyboard.left.shift+key.keyboard.left.control+key.keyboard.left.alt'
type ArmorSlot = 'HEAD' | 'CHEST' | 'LEGS' | 'FEET'
type TitleType = 'TITLE' | 'SUBTITLE' | 'ACTIONBAR'
type BlockUpdateType = 'STATE' | 'ENTITY'
type BossBarUpdateType = 'ADD' | 'REMOVE' | 'UPDATE_PERCENT'
| 'UPDATE_NAME' | 'UPDATE_STYLE' | 'UPDATE_PROPERTIES'
type HandledScreenName =
| '1 Row Chest'
| '2 Row Chest'
| '3 Row Chest'
| '4 Row Chest'
| '5 Row Chest'
| '6 Row Chest'
| '3x3 Container'
| 'Anvil'
| 'Beacon'
| 'Blast Furnace'
| 'Brewing Stand'
| 'Crafting Table'
| 'Enchanting Table'
| 'Furnace'
| 'Grindstone'
| 'Hopper'
| 'Loom'
| 'Villager'
| 'Shulker Box'
| 'Smithing Table'
| 'Smoker'
| 'Cartography Table'
| 'Stonecutter'
| 'Survival Inventory'
| 'Horse'
| 'Creative Inventory'
//--- runtime generates
// class_3675
type Key =
| 'key.keyboard.f1'
| 'key.keyboard.f2'
| 'key.keyboard.f3'
| 'key.keyboard.f4'
| 'key.keyboard.f5'
| 'key.keyboard.f6'
| 'key.keyboard.f7'
| 'key.keyboard.f8'
| 'key.keyboard.f9'
| 'key.keyboard.f10'
| 'key.keyboard.f11'
| 'key.keyboard.f12'
| 'key.keyboard.f13'
| 'key.keyboard.f14'
| 'key.keyboard.f15'
| 'key.keyboard.f16'
| 'key.keyboard.f17'
| 'key.keyboard.f18'
| 'key.keyboard.f19'
| 'key.keyboard.f20'
| 'key.keyboard.f21'
| 'key.keyboard.f22'
| 'key.keyboard.f23'
| 'key.keyboard.f24'
| 'key.keyboard.f25'
| 'key.keyboard.0'
| 'key.keyboard.1'
| 'key.keyboard.2'
| 'key.keyboard.3'
| 'key.keyboard.4'
| 'key.keyboard.5'
| 'key.keyboard.6'
| 'key.keyboard.7'
| 'key.keyboard.8'
| 'key.keyboard.9'
| 'key.keyboard.a'
| 'key.keyboard.b'
| 'key.keyboard.c'
| 'key.keyboard.d'
| 'key.keyboard.e'
| 'key.keyboard.f'
| 'key.keyboard.g'
| 'key.keyboard.h'
| 'key.keyboard.i'
| 'key.keyboard.j'
| 'key.keyboard.k'
| 'key.keyboard.l'
| 'key.keyboard.m'
| 'key.keyboard.n'
| 'key.keyboard.o'
| 'key.keyboard.p'
| 'key.keyboard.q'
| 'key.keyboard.r'
| 'key.keyboard.s'
| 'key.keyboard.t'
| 'key.keyboard.u'
| 'key.keyboard.v'
| 'key.keyboard.w'
| 'key.keyboard.x'
| 'key.keyboard.y'
| 'key.keyboard.z'
| 'key.keyboard.keypad.0'
| 'key.keyboard.keypad.1'
| 'key.keyboard.keypad.2'
| 'key.keyboard.keypad.3'
| 'key.keyboard.keypad.4'
| 'key.keyboard.keypad.5'
| 'key.keyboard.keypad.6'
| 'key.keyboard.keypad.7'
| 'key.keyboard.keypad.8'
| 'key.keyboard.keypad.9'
| 'key.keyboard.keypad.add'
| 'key.keyboard.keypad.decimal'
| 'key.keyboard.keypad.enter'
| 'key.keyboard.keypad.equal'
| 'key.keyboard.keypad.multiply'
| 'key.keyboard.left.alt'
| 'key.keyboard.left.bracket'
| 'key.keyboard.left.control'
| 'key.keyboard.left.shift'
| 'key.keyboard.left.win'
| 'key.keyboard.right.alt'
| 'key.keyboard.right.bracket'
| 'key.keyboard.right.control'
| 'key.keyboard.right.shift'
| 'key.keyboard.right.win'
| 'key.keyboard.208897'
| 'key.keyboard.212993'
| 'key.keyboard.212995'
| 'key.keyboard.apostrophe'
| 'key.keyboard.backslash'
| 'key.keyboard.backspace'
| 'key.keyboard.caps.lock'
| 'key.keyboard.comma'
| 'key.keyboard.delete'
| 'key.keyboard.down'
| 'key.keyboard.end'
| 'key.keyboard.enter'
| 'key.keyboard.equal'
| 'key.keyboard.escape'
| 'key.keyboard.grave.accent'
| 'key.keyboard.home'
| 'key.keyboard.insert'
| 'key.keyboard.left'
| 'key.keyboard.minus'
| 'key.keyboard.num.lock'
| 'key.keyboard.page.down'
| 'key.keyboard.page.up'
| 'key.keyboard.pause'
| 'key.keyboard.period'
| 'key.keyboard.print.screen'
| 'key.keyboard.right'
| 'key.keyboard.scroll.lock'
| 'key.keyboard.semicolon'
| 'key.keyboard.slash'
| 'key.keyboard.space'
| 'key.keyboard.tab'
| 'key.keyboard.up'
| 'key.mouse.left'
| 'key.mouse.middle'
| 'key.mouse.right'
// Java.from(Client.getGameOptions().getRaw().field_1839).map(k => k.method_1431())
// option.allKeys.map(key.getTranslationKey())
type Bind =
| 'key.attack'
| 'key.use'
| 'key.forward'
| 'key.left'
| 'key.back'
| 'key.right'
| 'key.jump'
| 'key.sneak'
| 'key.sprint'
| 'key.drop'
| 'key.inventory'
| 'key.chat'
| 'key.playerlist'
| 'key.pickItem'
| 'key.command'
| 'key.socialInteractions'
| 'key.screenshot'
| 'key.togglePerspective'
| 'key.smoothCamera'
| 'key.fullscreen'
| 'key.spectatorOutlines'
| 'key.swapOffhand'
| 'key.saveToolbarActivator'
| 'key.loadToolbarActivator'
| 'key.advancements'
| 'key.hotbar.1'
| 'key.hotbar.2'
| 'key.hotbar.3'
| 'key.hotbar.4'
| 'key.hotbar.5'
| 'key.hotbar.6'
| 'key.hotbar.7'
| 'key.hotbar.8'
| 'key.hotbar.9'
| 'key.meteor-client.open-gui'
| 'key.meteor-client.open-commands'
| 'jsmacros.menu'
| 'key.modmenu.open_menu'
| 'gui.xaero_switch_waypoint_set'
| 'gui.xaero_instant_waypoint'
| 'gui.xaero_toggle_slime'
| 'gui.xaero_toggle_grid'
| 'gui.xaero_toggle_waypoints'
| 'gui.xaero_toggle_map_waypoints'
| 'gui.xaero_toggle_map'
| 'gui.xaero_enlarge_map'
| 'gui.xaero_waypoints_key'
| 'gui.xaero_zoom_in'
| 'gui.xaero_zoom_out'
| 'gui.xaero_new_waypoint'
| 'gui.xaero_display_all_sets'
| 'gui.xaero_toggle_light_overlay'
| 'gui.xaero_toggle_entity_radar'
| 'gui.xaero_reverse_entity_radar'
| 'gui.xaero_toggle_manual_cave_mode'
| 'gui.xaero_alternative_list_players'
| 'gui.xaero_toggle_pac_players'
| 'gui.xaero_toggle_pac_chunk_claims'
| 'gui.xaero_minimap_settings'
// Registry.field_25933
type Biome = string
// Registry.field_11156
type Sound = string
// Registry.field_11142
type ItemId = string
// collect through items
type ItemTag =
| 'c:axes'
| 'c:black_dyes'
| 'c:blue_dyes'
| 'c:bows'
| 'c:brown_dyes'
| 'c:coal'
| 'c:copper_ingots'
| 'c:cyan_dyes'
| 'c:diamonds'
| 'c:dyes'
| 'c:emeralds'
| 'c:empty_buckets'
| 'c:foods'
| 'c:glass_blocks'
| 'c:glass_panes'
| 'c:gold_ingots'
| 'c:gray_dyes'
| 'c:green_dyes'
| 'c:hoes'
| 'c:iron_ingots'
| 'c:lapis'
| 'c:lava_buckets'
| 'c:light_blue_dyes'
| 'c:light_gray_dyes'
| 'c:lime_dyes'
| 'c:magenta_dyes'
| 'c:milk_buckets'
| 'c:netherite_ingots'
| 'c:orange_dyes'
| 'c:ores'
| 'c:pickaxes'
| 'c:pink_dyes'
| 'c:potions'
| 'c:purple_dyes'
| 'c:quartz'
| 'c:quartz_ores'
| 'c:raw_copper_blocks'
| 'c:raw_copper_ores'
| 'c:raw_gold_blocks'
| 'c:raw_gold_ores'
| 'c:raw_iron_blocks'
| 'c:raw_iron_ores'
| 'c:red_dyes'
| 'c:redstone_dusts'
| 'c:shears'
| 'c:shields'
| 'c:shovels'
| 'c:shulker_boxes'
| 'c:spears'
| 'c:swords'
| 'c:water_buckets'
| 'c:white_dyes'
| 'c:yellow_dyes'
| 'minecraft:acacia_logs'
| 'minecraft:anvil'
| 'minecraft:arrows'
| 'minecraft:axolotl_tempt_items'
| 'minecraft:banners'
| 'minecraft:beacon_payment_items'
| 'minecraft:beds'
| 'minecraft:birch_logs'
| 'minecraft:boats'
| 'minecraft:buttons'
| 'minecraft:candles'
| 'minecraft:chest_boats'
| 'minecraft:cluster_max_harvestables'
| 'minecraft:coal_ores'
| 'minecraft:coals'
| 'minecraft:compasses'
| 'minecraft:completes_find_tree_tutorial'
| 'minecraft:copper_ores'
| 'minecraft:creeper_drop_music_discs'
| 'minecraft:creeper_igniters'
| 'minecraft:crimson_stems'
| 'minecraft:dampens_vibrations'
| 'minecraft:dark_oak_logs'
| 'minecraft:diamond_ores'
| 'minecraft:dirt'
| 'minecraft:doors'
| 'minecraft:emerald_ores'
| 'minecraft:fence_gates'
| 'minecraft:fences'
| 'minecraft:fishes'
| 'minecraft:flowers'
| 'minecraft:fox_food'
| 'minecraft:freeze_immune_wearables'
| 'minecraft:gold_ores'
| 'minecraft:ignored_by_piglin_babies'
| 'minecraft:iron_ores'
| 'minecraft:jungle_logs'
| 'minecraft:lapis_ores'
| 'minecraft:leaves'
| 'minecraft:lectern_books'
| 'minecraft:logs'
| 'minecraft:logs_that_burn'
| 'minecraft:mangrove_logs'
| 'minecraft:music_discs'
| 'minecraft:non_flammable_wood'
| 'minecraft:oak_logs'
| 'minecraft:piglin_food'
| 'minecraft:piglin_loved'
| 'minecraft:piglin_repellents'
| 'minecraft:planks'
| 'minecraft:rails'
| 'minecraft:redstone_ores'
| 'minecraft:sand'
| 'minecraft:saplings'
| 'minecraft:signs'
| 'minecraft:slabs'
| 'minecraft:small_flowers'
| 'minecraft:soul_fire_base_blocks'
| 'minecraft:spruce_logs'
| 'minecraft:stairs'
| 'minecraft:stone_bricks'
| 'minecraft:stone_crafting_materials'
| 'minecraft:stone_tool_materials'
| 'minecraft:tall_flowers'
| 'minecraft:terracotta'
| 'minecraft:trapdoors'
| 'minecraft:walls'
| 'minecraft:warped_stems'
| 'minecraft:wart_blocks'
| 'minecraft:wooden_buttons'
| 'minecraft:wooden_doors'
| 'minecraft:wooden_fences'
| 'minecraft:wooden_pressure_plates'
| 'minecraft:wooden_slabs'
| 'minecraft:wooden_stairs'
| 'minecraft:wooden_trapdoors'
| 'minecraft:wool'
| 'minecraft:wool_carpets'
// Registry.field_11146
type BlockId = string
// collect through blocks
type BlockTag = string
// Registry.field_11145
type EntityId = string
// Registry.field_17597
type RecipeId = string
// class_1934.method_8381
type Gamemode = 'adventure' | 'creative' | 'spectator' | 'survival'
// Registry.field_25490
type Dimension = string
// s.getClass().getName()
// s.getTitle()
type ScreenName =// string
| HandledScreenName
| 'unknown'
// | ScreenClass
// Registry.field_17429
type ScreenClass = string
// class_1269.toString
type ActionResult = 'CONSUME' | 'CONSUME_PARTIAL' | 'FAIL' | 'PASS' | 'SUCCESS'
// class_1282.method_5525
type DamageSource =
| 'cactus'
| 'cramming'
| 'dragonBreath'
| 'drown'
| 'dryout'
| 'fall'
| 'flyIntoWall'
| 'freeze'
| 'generic'
| 'hotFloor'
| 'inFire'
| 'inWall'
| 'lava'
| 'lightningBolt'
| 'magic'
| 'onFire'
| 'outOfWorld'
| 'stalagmite'
| 'starve'
| 'sweetBerryBush'
| 'wither'
// same as screenName but check if is container
type InventoryType =// string
| HandledScreenName
// Registry.field_11159
type StatusEffectId = string
// class_3619.toString
type PistonBehaviour = 'BLOCK' | 'DESTROY' | 'IGNORE' | 'NORMAL' | 'PUSH_ONLY'
// class_1297$class_5529.toString
type EntityUnloadReason =
| 'CHANGED_DIMENSION'
| 'DISCARDED'
| 'KILLED'
| 'UNLOADED_TO_CHUNK'
| 'UNLOADED_WITH_PLAYER'
// class_1259$class_1260.method_5421.toUpperCase
type BossBarColor = 'BLUE' | 'GREEN' | 'PINK' | 'PURPLE' | 'RED' | 'WHITE' | 'YELLOW'
// class_1259$class_1261.method_5425.toUpperCase
type BossBarStyle = 'NOTCHED_10' | 'NOTCHED_12' | 'NOTCHED_20' | 'NOTCHED_6' | 'PROGRESS'
// class_2558$class_2559.method_10846
type TextClickAction =
| 'change_page'
| 'copy_to_clipboard'
| 'open_file'
| 'open_url'
| 'run_command'
| 'suggest_command'
// class_2568$class_5247.method_27674
type TextHoverAction = 'show_entity' | 'show_item' | 'show_text'
// class_3854.toString
type VillagerStyle = 'desert' | 'jungle' | 'plains' | 'savanna' | 'snow' | 'swamp' | 'taiga'
// class_3852.comp_818
type VillagerProfession =
| 'armorer'
| 'butcher'
| 'cartographer'
| 'cleric'
| 'farmer'
| 'fisherman'
| 'fletcher'
| 'leatherworker'
| 'librarian'
| 'mason'
| 'nitwit'
| 'none'
| 'shepherd'
| 'toolsmith'
| 'weaponsmith'
